### ISSUE TITLE
Command syncing

### ISSUE THREAD

**Issue by MattDemers** [CyberHumi/Chatbot-Scripts#3]
Hi there. I have both this script running and Lumia Cove, which is a similar bot, only with the Philips Hue system. What I'm looking for is to be able to unify the commands, so when a user types one command, they can change both light systems.

With this script, the format much be "[command] [input]". What I'd like to do is use "[command][input]"

For instance, I must do "!lights White" or "! White" for a scene. I would like to be able to do "!White". Is this possible? On the other bot, I cannot add a longer key to add "!lights [input]" to the system.

Thanks! Not sure if this is possible.

**Comment by CyberHumi** [comment]
Update your script to version 1.6. There is now an option to add up to 10 additional chat commands.

![naec_additionalchatcmds](https://user-images.githubusercontent.com/40529356/50261351-7f196480-040c-11e9-8363-13cbd0dc26d2.PNG)

**Comment by MattDemers** [comment]
Thank you!
