### ISSUE TITLE
Using chat command you should be able to choose effect

### ISSUE THREAD

**Issue by ForthtuN** [CyberHumi/Chatbot-Scripts#4]
Thanks for a great nanoleaf plugin! It seems to work very well after setting it up and im happy with it!

I would just like to see if you could be able to make the "Chat command" have a custom effect instead of going to the "default" one. You could only choose the effects in the "additional chat commands" but they can't be configured with any points or such.

Keep up the good work!

**Comment by CyberHumi** [comment]
The chat commands work as follows:
Under "Chat command" you define a command which need an effect name as a parameter, e.g. 
!nl Forest
!nl Color Burst

With the 'Additional commands' you assign the effect name to a chat command.
The other settings (points, permission, duration and cooldown) in "Chat command" apply to all chat commands.
